### ISSUE TITLE
Mixed use git may cause the repository cannot be accessed

### ISSUE THREAD

**Issue by fcharlie** [bozaro/git-as-svn#118]
![2016-11-16 12-02-25](https://cloud.githubusercontent.com/assets/6904176/20334381/901a68be-abf4-11e6-9ed1-6bc410050bf2.png)

Step 

1. Donwload https://github.com/bozaro/git-as-svn/releases/download/1.1.1/git-as-svn_1.1.1.zip
2. unzip git-as-svn_1.1.1.zip to /path/to/git-as-svn
3. vi config.example , change cacheConfig.path 
4. svn co svn://localhost/example
5. git clone file:///path/to/example.git
6. gitclonedir: touch hello &&git add hello &&git commit -m "add hello" &&git push
7. svndir: svn up .
8. gitclonedir: git reset commitid
9. example.git: git gc --pure=now
10. svndir: svn up .

So We can known, When A developer use git-as-svn on Gitlab Services,Many developers use the same warehouse, in part using SVN, in part using git, the team also have a PR, over time, will most likely be a developer cannot use svn to access this repository.

Simple strategy:

Remove cache from mapdb, remove refs on repository,after reload cache

**Comment by bozaro** [comment]
I do not understand what you are trying to play in this example...

Git-as-svn use special ref (refs/git-as-svn/v1) for keep svn commit order and hold revisions removed by git force push.
As I known, `git gc` must keep this commits, because thay have reference from `refs/git-as-svn/v1`. If I made a mistake at this point, then we can get this error after the force push.

I need some time to check `git gc` behaviour.

**Comment by fcharlie** [comment]
refs/git-as-svn/v1 not keep current commit, it is keep svn modify info's commit,

1. git cat-file -p see ref commit
2. use git cat-file -p see tree.

![2016-11-17 18-34-58](https://cloud.githubusercontent.com/assets/6904176/20386012/b47629f4-acf4-11e6-911f-5e32f72284d6.png)



When git push --force, some commit is offline, git gc maybe cleanup it.

**Comment by fcharlie** [comment]
git gc call pack-object, if objects (blob commit tree) not add to pack, those objects is dangling objects

When commit in tree, pack-object does not recursively parses the commit, submodule and this is the same.
