### ISSUE TITLE
Support connecting to GitLab as unpriveleged user

### ISSUE THREAD

**Issue by mbr** [bozaro/git-as-svn#119]
`git-as-svn` tries to use `/api/v3/projects/all` to access projects available. When given a non-admin access token (from a user specifically created for `git-as-svn`), this will cause an HTTP 403 error.

An alternative is using the endpoint `/api/v3/projects`, which only lists projects the user has access to.

**Comment by slonopotamus** [comment]
Okay, there are deeper problems. We also call /api/v3/hooks.

**Comment by slonopotamus** [comment]
I don't see much value in this task. git-as-svn uses direct file access to repository files so using unprivileged user for GitLab access doesn't add much security and doesn't open new usecases.
