### ISSUE TITLE
svnserve.conf and SASL support

### ISSUE THREAD

**Issue by vsdev** [bozaro/git-as-svn#125]
We are trying to turn off the support for the SASL for the repository but we do not know how to specify the config file svnserve.conf for bozaro system. Could you tell us is it possible to specify a config file svnserve.conf for the repository?

**Comment by slonopotamus** [comment]
SASL is the only currently supported way if you authenticate users via LDAP. For local user db (when you specify logins/passwords directly in git-as-svn), we use CRAM-MD5 that works without SASL in svn clients.

**Comment by vsdev** [comment]
I'm looking for a solution to the problem with the Unreal Engine 4 SVN frontend. 
The problem lies precisely in the authentication method using SASL (4.15 version and previous).
Disabling SASL (svnserve.conf) for a standard SVN repo (not git-as-svn) solved the problem. 
But after your comment about the method of authentication in the case of a local db, it seems to me that the problem is more serious.
