### ISSUE TITLE
gitlab 10.0

### ISSUE THREAD

**Issue by tozor** [bozaro/git-as-svn#133]
После обновления гитлаба на 10 ветку, перестало работать, пришлось временно откатываться. 
Committing transaction...:   
Error: Commit failed (details follow):  
Error: svn: E165001: Commit blocked by hook with output:  
Error:   
Error: If you want to break the lock, use the 'Check For Modifications' dialog or the repository browser.  
Completed!:

**Comment by tozor** [comment]
Файл не залочен ничем, причем оно как бы вылаживает, несмотря на ошибку. В итоге файл на который ругалось остается не закомиченым, а в логе новая ревизия.

**Comment by slonopotamus** [comment]
Какая конкретно версия гитлаба?

**Comment by slonopotamus** [comment]
Duplicate of #160.

**Comment by slonopotamus** [comment]
Please, try git-as-svn 1.2.0, this bug is expected to be fixed there.
