### ISSUE TITLE
Get Git Attributes from $GIT_DIR/info. aka: $GIT_DIR/info/attributes

### ISSUE THREAD

**Issue by cicerocomp** [bozaro/git-as-svn#173]
> When deciding what attributes are assigned to a path, Git consults $GIT_DIR/info/attributes file (which has the highest precedence), .gitattributes file in the same directory as the path in question, and its parent directories up to the toplevel of the work tree

ref: https://git-scm.com/docs/gitattributes

**Comment by slonopotamus** [comment]
I don't see how this applies to git-as-svn. Git-as-svn is designed to sit on top bare repo where both git users and svn users commit stuff into. But .git/info/attrubutes isn't shared from server to clients so git clients are unaware of its existence, it only makes effect when placed on client. If you want attributes settings to be used by everyone using particular repository, you need to commit them into .gitattributes.
