### ISSUE TITLE
Server fails to start with Fatal error: Cannot create property=repositoryMapping for JavaBean=svnserver.config.Config

### ISSUE THREAD

**Issue by huguesdk** [bozaro/git-as-svn#180]
This is maybe due to my configuration, but I wasn’t able to launch the server. I followed the quick start guide, (launching with the example config) but I get the following error:

```
2018-08-24T13:41:45,949  INFO [main] (Main.java:34) - Git as svn version: 1.4.0, 852d0b33301f9a61310cd1a9af2c631ae3f80d06
2018-08-24T13:41:46,106 ERROR [main] (Main.java:59) - Fatal error: Cannot create property=repositoryMapping for JavaBean=svnserver.config.Config@15ff3e9e
 in 'reader', line 1, column 1:
    !config:
    ^
Cannot create property=repositories for JavaBean=svnserver.config.RepositoryListMappingConfig@7fa98a66
 in 'reader', line 30, column 20:
    repositoryMapping: !listMapping
                       ^
Cannot create property=repository for JavaBean=svnserver.config.RepositoryListMappingConfig$Entry@1a451d4d
 in 'reader', line 33, column 7:
          access: !acl
          ^
Cannot create property=extensions for JavaBean=svnserver.config.GitRepositoryConfig@62150f9e
 in 'reader', line 45, column 19:
          repository: !git
                      ^
Can't construct a java object for !api; exception=Invalid tag: !api
 in 'reader', line 65, column 13:
              - !api
                ^
```
and this goes on for several hundreds of lines. I’m on GNU/Linux, running version 1.4.0 from the tbz2 release archive. I tried on another machine with the latest Java RE, but the result is the same. I tried version 1.3.0 and also the zip archive, but it’s always the same.

Any help here please? Sorry if it’s a newbie question, I almost never run Java apps…

**Comment by slonopotamus** [comment]
I'm assuming you're using `config-local.example`. Either add `--unsafe` command-line argument or remove `!api` sections (there are two of them, one in repository extensions and one in shared section).

I'm not currently ready to explain why `!api` is needed at all so won't be closing this issue until figure that out.

**Comment by huguesdk** [comment]
Indeed, it works with `--unsafe`. Thanks!

**Comment by slonopotamus** [comment]
Okay, `!api` is needed for `git-lfs-authenticate` script. Not sure this is a good thing to require `--unsafe` for default config, but let's leave things as they are for now.
