### ISSUE TITLE
Migrate existing svn repo to git-as-svn?

### ISSUE THREAD

**Issue by db4** [bozaro/git-as-svn#182]
Is it possible? I would like to preserve existing SVN commit numbers and not break existing SVN client working copies.

**Comment by slonopotamus** [comment]
There is (almost) nothing special in git-as-svn repository compared to normal git repository. So you can just use usual stuff for general svn->git conversion (for example, `git svn clone`). You'll also want to [set up .gitattributes](http://bozaro.github.io/git-as-svn/htmlsingle/en_US/#d5e198) to avoid Git/SVN behavior mismatch.

As for breaking SVN client existing working copies... I *highly* doubt that's possible. Even a minor incompatibility between repo histories will mean working copy is SNAFU. Repo UUID much match, all files must match byte-to-byte, all files SVN properties must match. If anything of that fails, sooner or later SVN client will encounter a situation where it disagrees with server about some file state and will just helplessly error out.

**Comment by db4** [comment]
@slonopotamus, thanks a lot for your answer. So if I convert an existing SVN repo (say, containing SVN revisions 1-1000) using `svn git` , will SVN client be able to checkout an old revision (say 100) from the repo via git-as-svn?

**Comment by slonopotamus** [comment]
git-as-svn fully exposes a branch (`master` by default), starting from the very first commit, by walking through first parents of each commit. So if you merge some FeatureBranch into master, SVN users will see a single merge commit that brings in branch changes into master, but not see individial commits on FeatureBranch.

Maybe you just want to [play with git-as-svn](https://github.com/bozaro/git-as-svn#run-from-binaries)? It already comes with example config/repo that can be used for experiments.

**Comment by db4** [comment]
OK, that makes sense.  Thanks a lot again.
