### ISSUE TITLE
Setup signing on Bintray

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/git-as-svn#195]
Currently apt-get warns that Bintray repo isn't signed with GPG.

See https://github.com/ponylang/ponyc/issues/1825 for solving the same issue.

Most likely, you just need to add GPG key to repository settings on Bintray.

**Comment by bozaro** [comment]
GPG Public Key: https://bintray.com/user/downloadSubjectPublicKey?username=bozaro

**Comment by slonopotamus** [comment]
I think everything is good here.
