### ISSUE TITLE
GiteaIntegrationTest.testGiteaMapping fails with latest Gitea

### ISSUE THREAD

**Issue by slonopotamus** [bozaro/git-as-svn#217]
https://travis-ci.org/bozaro/git-as-svn/jobs/460845508

    java.lang.AssertionError: Expected SVNAuthenticationException to be thrown, but nothing was thrown
        at org.testng.Assert.expectThrows(Assert.java:1394)
        at org.testng.Assert.assertThrows(Assert.java:1364)
        at svnserver.ext.gitea.GiteaIntegrationTest.testGiteaMapping(GiteaIntegrationTest.java:257)

This didn't happen two days ago: https://travis-ci.org/bozaro/git-as-svn/builds/459794680

@zeripath

**Comment by zeripath** [comment]
hmm... I think this may have something to do with https://github.com/go-gitea/gitea/commit/eabbddcd98717ef20d8475e819f403c50f4a9787

I think this probably counts as a bug in a gitea PR that I just approved... Damn...

**Comment by slonopotamus** [comment]
That's kinda funny that test that you wrote for git-as-svn found a bug that you also merged into gitea ;)

So, if I read test correctly, seems like user got access to repo he isn't supposed to have.

**Comment by zeripath** [comment]
So it turns out that I think that Gitea push fixed a bug I was relying on in my code here!

**Comment by slonopotamus** [comment]
I believe that sudo that silently succeeds with an empty string might be a dangerous thing and a source of security issues. What has it in fact happened here.
