### ISSUE TITLE
Gitea,Command execution error: svn: E165001: Invalid svn properties on files:

### ISSUE THREAD

**Issue by yu66433** [bozaro/git-as-svn#330]
Git： Gitea Docker Image
Git-As-SVN: git-as-svn_1.23.1

sry my en,

i create a repo, and just only a text file,but There was an error when I commit it ... TT

![image](https://user-images.githubusercontent.com/5615986/75523742-89d77c80-5a47-11ea-9843-650dfdca4ca6.png)

![image](https://user-images.githubusercontent.com/5615986/75523755-9360e480-5a47-11ea-909b-5f1820db474b.png)

![image](https://user-images.githubusercontent.com/5615986/75523861-ce631800-5a47-11ea-8976-976d776ee053.png)

**Comment by slonopotamus** [comment]
1. Add `*.txt eol=native` to `.gitattributes` and commit it
2. `svn up` at the root of your working copy.
3. Now, your svn automatically knows that it should add `svn:eol-style=native` property on txt files.
4. `svn add <file you want to add through svn>`
5. `svn commit`

There is a long story about mapping `.gitattributes` to svn properties. Possibly I should improve [documentation on it](https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_file_gitattributes).

**Comment by yu66433** [comment]
> 1. Add `*.txt eol=native` to `.gitattributes` and commit it
> 2. `svn up` at the root of your working copy.
> 3. Now, your svn automatically knows that it should add `svn:eol-style=native` property on txt files.
> 4. `svn add <file you want to add through svn>`
> 5. `svn commit`
> 
> There is a long story about mapping `.gitattributes` to svn properties. Possibly I should improve [documentation on it](https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_file_gitattributes).
> 
> Unfortunately, we _cannot_ map `* -text` entry from `.gitattributes` to `svn:auto-props` because SVN doesn't have a way to **override** properties for specific file masks. Instead, it attempts to apply _all_ matching masks and fails miserably.

thank your reply！

I tried your method, but it didn't work

1. I created a repository for TS03

2. Create a ".gitattribute" file with only "*.txt eol=native ".
![image](https://user-images.githubusercontent.com/5615986/75659518-1632ab00-5ca5-11ea-8e6e-51aa694ac4ee.png)

3. check out TS02 with SVN command

4. Add a text file 
![image](https://user-images.githubusercontent.com/5615986/75659605-35c9d380-5ca5-11ea-9c2a-9d0ae2c89a44.png)

5. Use SVN add

6, SVN ci
![image](https://user-images.githubusercontent.com/5615986/75659652-4d08c100-5ca5-11ea-9f8b-444908548d85.png)

i don't know why Actual is empty 。


（1）、I'm trying to add "* -text" to ".gitattrubute"

![image](https://user-images.githubusercontent.com/5615986/75659913-cacccc80-5ca5-11ea-8741-e71a85e2a3e7.png)

（2）、svn up work copy and submit the TXT file, but it still fails.

![image](https://user-images.githubusercontent.com/5615986/75659884-bab4ed00-5ca5-11ea-9db4-b4e524381f64.png)

**Comment by slonopotamus** [comment]
1. Please show your `svn --version`
2. Please, show `svn pl -v .` output from root of working copy.

**Comment by slonopotamus** [comment]
Sorry, I gave you wrong information. Sometimes SVN/Git stuff mixes up in my head :( `eol=native` is invalid syntax in `.gitattributes`. You say `*.txt	text` there`, according to [docs](https://git-scm.com/docs/gitattributes).

**Comment by yu66433** [comment]
> Sorry, I gave you wrong information. Sometimes SVN/Git stuff mixes up in my head :(
> 
> `eol=native` is invalid syntax in `.gitattributes`. You say `*.txt text` there, according to [docs](https://git-scm.com/docs/gitattributes).

i just test ,but faild
![image](https://user-images.githubusercontent.com/5615986/75660768-1f247c00-5ca7-11ea-9bd9-cdb59c77803f.png)

**Comment by yu66433** [comment]
> 1. Please show your `svn --version`
> 2. Please, show `svn pl -v .` output from root of working copy.


![image](https://user-images.githubusercontent.com/5615986/75660966-6ca0e900-5ca7-11ea-954d-54c0e35ee47c.png)

**Comment by yu66433** [comment]
Maybe this is my fate...

**Comment by slonopotamus** [comment]
Did you `svn add` file after doing `svn up` or before? If before, undo `svn add` (via `svn revert`) and redo `svn add`. Next time you `svn add` .txt files, they will Just Work.

The key to this props issue is: svn working copy needs to know (via `svn:auto-props`, as you see in output of `svn pl -v <wc root>`) what props to apply to what files by the time you do `svn add`. If this is the case, it knows what properties to apply to file.

**Comment by yu66433** [comment]
> Did you `svn add` file after doing `svn up` or before? If before, undo `svn add` (via `svn revert`) and redo `svn add`. Next time you `svn add` .txt files, they will Just Work.
> 
> The key to this props issue is: svn working copy needs to know (via `svn:auto-props`, as you see in output of `svn pl -v <wc root>`) what props to apply to what files by the time you do `svn add`. If this is the case, it knows what properties to apply to file.

thank you  so much , it works!
It is indeed ,i did `svn add` before `svn up`.
when i `svn revert <filename>` and  readd `svn add <file>`,it works!

**Comment by yu66433** [comment]
thank you !!!!

**Comment by slonopotamus** [comment]
I've updated docs on svn properties: https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_props
Hopefully, it provides enough info.
