### ISSUE TITLE
Gitlab 12.9 hooks issues

### ISSUE THREAD

**Issue by db4** [bozaro/git-as-svn#337]
(a separate issue from https://github.com/bozaro/git-as-svn/issues/271#issuecomment-606781109)

@slonopotamus 
> Yes. This stuff was added to docs: https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_configuration

Looks like this doesn't work anymore. After upgrading Gitlab to 12.9.1-ce.0 and git-as-svn to 1.25.0 all my svn commits fail due to a hook issue:
```
Transmitting file data .done
Committing transaction...
svn: E165001: Commit failed (details follow):
svn: E165001: Hook /opt/gitlab/embedded/service/gitaly-ruby/git-hooks/pre-receive failed with output:
/opt/gitlab/embedded/service/gitaly-ruby/git-hooks/pre-receive: 4: exec: /gitaly-hooks: not found
```
`pre-receive` is a link to `gitlab-shell-hook`:
```bash
#!/bin/sh

# This is the single source of truth for where Gitaly's embedded Git hooks are.
exec "$GITALY_BIN_DIR/gitaly-hooks" "$(basename $0)" "$@"
```
The problem is that `GITALY_BIN_DIR` is not defined on its invocation. I tried to define it in `/etc/default/git-as-svn` 
`GITALY_BIN_DIR=/opt/gitlab/embedded/bin`, but it doesn't help. Any idea how to fix this?

**Comment by db4** [comment]
@slonopotamus 
> Also, did you restart git-as-svn after changing /etc/default/git-as-svn?

Yes, I did. It fails differently when `GITALY_BIN_DIR` is set:
```
Transmitting file data .done
Committing transaction...
svn: E165001: Commit failed (details follow):
svn: E165001: Hook /opt/gitlab/embedded/service/gitaly-ruby/git-hooks/pre-receive failed with output:
error executing git hook
```

**Comment by slonopotamus** [comment]
This is what you need: https://github.com/bozaro/git-as-svn/commit/cb6e852b11601839aad1ea60ce50e5047fc13a38#diff-d1b43a4622b8fe291cbc78882cdcdb00R34-R35

**Comment by db4** [comment]
@slonopotamus 
I confirm that the fix works. Thanks a lot!
