### ISSUE TITLE
Install test.  Repository branch not found

### ISSUE THREAD

**Issue by MichaelJCole** [bozaro/git-as-svn#342]
Hi, I'm following through the [documentation](https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_git_as_svn_package) and noticed this:

I can curl 3690, but not `svn ls` or `svn checkout` it (as recommended in the docs)

```
michael@DESKTOP-ITU0U36 ~/scm
$  svn ls --username test --password test svn://teams.project.com/example/
svn: E170013: Unable to connect to a repository at URL 'svn://teams.project.com/example'
svn: E210005: Repository branch not found. Use `svn relocate svn://teams.project.com/example/master` to fix your working copy

michael@DESKTOP-ITU0U36 ~/scm
$  curl http://teams.project.com:3690
( success ( 2 2 ( ) ( accepts-svndiff2 svndiff1 depth edit-pipeline log-revprops file-revs-reverse absent-entries inherited-props ) ) )

```

**Comment by slonopotamus** [comment]
You're using the wrong URL. it is `svn://<host>/<repo>/<branch>`. git-as-svn is even telling you what URL you actually want to use: `svn://teams.project.com/example/master`

**Comment by MichaelJCole** [comment]
Hi @slonopotamus, that command was from the documentation.  Do you want documentation bugs?

https://bozaro.github.io/git-as-svn/htmlsingle/git-as-svn.html#_git_as_svn_package

```
To access the server, you can use the user:

Login: test

Password: test

You can check configuration with command like:

svn ls --username test --password test svn://localhost/example/
```

**Comment by slonopotamus** [comment]
This was just a leftover from pre-[1.12.0](https://github.com/bozaro/git-as-svn/releases/tag/1.12.0) era. Back in those dark ages each repo branch was set up independently in git-as-svn, so there was no common pattern for URLs.
