### ISSUE TITLE
GitLab 12.10.1 svn commit fails with E165001/Permission denied...

### ISSUE THREAD

**Issue by wehall** [bozaro/git-as-svn#347]
As of gitlab-ce-12.10.1, without GITALY_LOG_DIR=/var/log/gitlab/gitaly in /etc/default/git-as-svn, svn commits fail with E165001.  Error reported via client and in git-as-svn.log:

svn: E165001: Hook /opt/gitlab/embedded/service/gitaly-ruby/git-hooks/pre-receive failed with output:
/opt/gitlab/embedded/service/gitaly-ruby/gitlab-shell/lib/gitlab_logger.rb:42:in `initialize': Permission denied @ rb_sysopen - /opt/gitlab/embedded/service/gitlab-shell/gitlab-shell.log (Errno::EACCES)

Unclear if these should be set as well.  They are present (with these values) in git transactions, but svn commits appear to work if they are absent:
GITALY_LOG_LEVEL=
GITALY_LOG_FORMAT=json

**Comment by slonopotamus** [comment]
Thanks, this was included in 1.26.1 release
