### ISSUE TITLE
Empty directories patch

### ISSUE THREAD

**Issue by MichaelJCole** [bozaro/git-as-svn#352]
So if I try to commit an empty directory, I get `Empty directories is not supported:`

It looks like svn clients expect support for empty directories but git doesn't understand it.

What do you think of [this patch here](https://github.com/bwegh/git-as-svn/commit/f23036964517c4684fa55f93da37bb8cbef3fa06) to create a .keep file?

**Comment by slonopotamus** [comment]
This is a duplicate of #126. Please read comments there why such approach is a no-go.

**Comment by MichaelJCole** [comment]
Thanks, I'll comment there :-)
