### ISSUE TITLE
svn: E165001: Hook /opt/gitlab/embedded/service/gitaly-ruby/git-hooks/pre-receive failed with output: error executing git hook "error executing git hook" on svn commit...

### ISSUE THREAD

**Issue by wehall** [bozaro/git-as-svn#355]
gitlab-ce v13.1.1-ce svn commit fails as titled, 
"level=fatal msg="error when getting repository: GITALY_REPO not found" in /var/log/gitlab/gitaly/gitaly_hooks.log

git push environment includes  GITALY_REPO variable:
GITALY_REPO={"storageName":"default","relativePath":"@hashed/d4/73/d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35.git","glRepository":"project-2","glProjectPath":"root/testproject"}

**Comment by slonopotamus** [comment]
GitLab guys can't stop adding more and more env variables required to run hooks :(

**Comment by slonopotamus** [comment]
https://gitlab.com/gitlab-org/gitaly/-/issues/2902
In 13.2 this stuff is all messed up again :(

**Comment by slonopotamus** [comment]
This was fixed in git-as-svn 1.27.0
