### ISSUE TITLE
Create PR to SvnKit with fix for SVNUUIDGenerator.generateUUID()

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-as-svn#79]
SVNUUIDGenerator.generateUUID() generates non-unique value because bug in SVNUUIDGenerator.timestamp()

**Comment by fcharlie** [comment]
Your can use  UUID.randomUUID();

**Comment by bozaro** [comment]
https://issues.tmatesoft.com/issue/SVNKIT-607

**Comment by bozaro** [comment]
@fcharlie 
I use SvnKit and native svnserver in the tests to verify the identity of behavior.
Inside SvnKit generator SVNUUIDGenerator.generateUUID() is used, and because of this he sometimes behaves strangely.
Within this project, I do not use SVNUUIDGenerator.generateUUID() generator.

**Comment by bozaro** [comment]
Fixed in svnkit-1.8.11+
