### ISSUE TITLE
When I use git-as-svn PLAIN Auth, Update svn client 1.9.0 ,connect failed

### ISSUE THREAD

**Issue by fcharlie** [bozaro/git-as-svn#85]
Cannot negotiate authentication mechanism

PLAIN Auth: 
https://github.com/bozaro/git-as-svn/blob/master/src/main/java/svnserver/auth/PlainAuthenticator.java

**Comment by bozaro** [comment]
I install TortoiseSVN 1.9 locally and sucessfully "svn update" for "ldapUsers" and "localUsers" authentication.

I would like to clarify:

 * client operation system?
 * what SVN client used?
 * server userDB configuration type?

**Comment by fcharlie** [comment]
I replace Auth MD5 to PLAIN .

**Comment by bozaro** [comment]
I have not understand how reproduce the problem.
CramMD5Authenticator is used only for localUsers. But where did the client without the support of CRAM-MD5 is not clear to me.

**Comment by fcharlie** [comment]
I replace  
https://github.com/bozaro/git-as-svn/blob/master/src/main/java/svnserver/auth/LocalUserDB.java#L28  to
```
  private final Collection<Authenticator> authenticators = Collections.singleton(new PlainAuthenticator(new RemotePasswordChecker()));
```

**Comment by bozaro** [comment]
I undestand how solve the problem :)
I don't undestand how reproduce the problem.

**Comment by bozaro** [comment]
What is RemotePasswordChecker ?

**Comment by fcharlie** [comment]
so ,Can you tell me how to use the PLAIN authentication supports SVN 1.9 .

Simply use git-as-svn not able to reproduce this problem。
I need to get the user's email and password, and then through the gitlab API to request the server and get the user's information. During the authentication phase, I use replace CramMD5 with PLAIN. 
When I use the 1.8 version of the svn checkout repository, everything is OK, the most recent SVN release of 1.9.
when I used svn 1.9 checked out repository, appear this error "svn: E210007: Cannot negotiate authentication mechanism"

In fact this problem also occurs in  Eclipse svn plug(javahl based) to access the repository

###WireShark dump

```
( success ( 2 2 ( ) ( edit-pipeline svndiff1 absent-entries depth inherited-props log-revprops ) ) ) 
( 2 ( edit-pipeline svndiff1 absent-entries depth mergeinfo log-revprops ) 39:svn://localhost/hello/world 33:SVN/1.9.0 (x64-microsoft-windows) ( ) ) ( success ( ( PLAIN ) 15:git.oschina.net ) )
```

**Comment by slonopotamus** [comment]
According to your wireshark dump, server correctly announces that it accepts PLAIN autientication. Looks like your client cannot handle it. This can happen if svn is compiled without SASL support.

**Comment by bozaro** [comment]
@fcharlie 
Do you see: https://github.com/bozaro/git-as-svn/tree/gitlab ?

**Comment by fcharlie** [comment]
@slonopotamus  @bozaro I started modifying last year, and at that time no gitlab branch
Thanks

**Comment by bozaro** [comment]
@fcharlie 
In my case, TortoiseSVN works fine with PLAIN and CRAM-MD5 auth:
```
TortoiseSVN 1.9.0, Build 26652 - 64 Bit , 2015/08/03 19:33:09
Subversion 1.9.0, -release
apr 1.5.2
apr-util 1.5.4
serf 1.3.8
OpenSSL 1.0.2d 9 Jul 2015
zlib 1.2.8
SQLite 3.8.11.1
```

**Comment by fcharlie** [comment]
@bozaro  Thanks .

**Comment by slonopotamus** [comment]
So, @fcharlie, is your issue solved?

**Comment by fcharlie** [comment]
@slonopotamus 
Next week I will rewrite my branch  thanks.
